variables:
  COMPOSER_PROCESS_TIMEOUT: "900"

stages:
  - test

cache:
  key: $CI_PROJECT_ID
  paths:
    - /vendor

###########################################################################

test-job:
  stage: test
  only:
    - develop
    - master
  tags:
    - buildbox-php:1.0.X
  script:
    - composer install --ignore-platform-reqs
    - ./vendor/bin/phpunit tests

